version: '3'
services:
  front:
    image: node:12
    volumes:
      - ./front:/usr/src/service
    working_dir: /usr/src/service
    entrypoint: ./entrypoint.sh
    command: yarn run dev
    ports:
      - 3000:3000

  database:
    image: mariadb:bionic
    environment:
      MYSQL_USER: stravaganza
      MYSQL_PASSWORD: stravaganza
      MYSQL_DATABASE: stravaganza
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  composer:
    image: composer:latest
    volumes:
      - ./back:/opt/laravel
    working_dir: /opt/laravel
    command: sh -c "touch lock && composer install && rm lock"

  back:
    image: php:7.4-cli
    volumes:
      - ./back:/opt/laravel
    working_dir: /opt/laravel
    command: ./scripts/wait.sh php -S 0.0.0.0:8000 -t public
    ports:
      - 8000:8000
    links:
      - database
    depends_on:
      - composer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 5s
      retries: 5
