// tslint:disable
/**
 * Stravaganza
 * API for Stravaganza website
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: remy.huet@etu.utc.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api'
export * from './configuration'
