# This is a basic workflow to help you get started with Actions

name: Back CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    paths: 
      - "back/**"
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-back:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: setup-php
      uses: khs1994-docker/actions-setup-php@0.0.1
      with:
        php_version: 7.4.4
        php_type: composer

    - name: Set env
      run: cp .env.example .env
      working-directory: back

    # Runs a single command using the runners shell
    - name: Install dependences
      run: composer install
      working-directory: back
    
    - name: Run phpunit
      uses: php-actions/phpunit@v1
      with:
        config: back/phpunit.xml
        bootstrap: back/vendor/autoload.php
